# Generated by Django 4.2.7 on 2023-11-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='isActive2',
            field=models.BooleanField(default=True),
        ),
    ]
