# Generated by Django 4.2.7 on 2023-11-28 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0002_project_isactive2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='isActive2',
        ),
    ]
