# Generated by Django 4.2.7 on 2023-11-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0003_remove_project_isactive2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='modification_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='Database', max_length=50),
        ),
    ]
