# Generated by Django 4.2.7 on 2024-01-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0004_project_database_alter_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='database',
            field=models.FileField(default=None, null=True, upload_to='databases/'),
        ),
    ]
