# Generated by Django 4.2.7 on 2024-01-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0009_alter_project_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='database_separator',
            field=models.CharField(default=',', max_length=1),
        ),
    ]
