# Generated by Django 4.2.7 on 2024-01-25 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
        ('project_management', '0010_project_database_separator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='database_separator',
        ),
        migrations.AlterField(
            model_name='project',
            name='database',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.database'),
        ),
    ]
