# Generated by Django 4.2.7 on 2024-01-25 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
        ('project_management', '0011_remove_project_database_separator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='database',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.database'),
        ),
    ]
