# Generated by Django 4.2.7 on 2024-05-30 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0012_alter_project_database'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='database',
        ),
    ]
