# Generated by Django 4.2.7 on 2024-06-06 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prevision', '0001_initial'),
        ('project_management', '0013_remove_project_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='prevision_model',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='prevision.previsionmodel'),
        ),
    ]
