# Generated by Django 4.2.7 on 2024-06-08 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prevision', '0001_initial'),
        ('project_management', '0014_project_prevision_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='prevision_model',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='prevision.previsionmodel'),
        ),
    ]
