Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "Backend-CarcaraQSAR"
  end
  
  # Encaminhamento de portas para acessar o servidor Django
  config.vm.network "forwarded_port", guest: 1234, host: 1234

  config.vm.provision "shell", inline: <<-SHELL
    # Atualiza a lista de pacotes
    sudo apt-get update

    # Instalação de dependências do Django
    sudo apt-get install -y python3.10 python3.10-pip python3.10-venv
    python3 --version

    # Criação de ambiente virtual para o projeto Django
    python3 -m venv myenv
    source myenv/bin/activate

    # Instalação de dependências
    git clone https://github.com/rosalvoneto/CarcaraQSAR
    cd CarcaraQSAR/backend/backend
    pip install -r requirements.txt

    # Execução do backend com o gunicorn
    sh startup.sh
  SHELL
end
