# Generated by Django 4.2.7 on 2024-06-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrevisionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_file', models.FileField(blank=True, null=True, upload_to='models/')),
                ('variables', models.JSONField(default=list)),
            ],
        ),
    ]
