# Generated by Django 4.2.7 on 2024-06-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prevision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='previsionmodel',
            name='project_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
