# Generated by Django 4.2.7 on 2024-06-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prevision', '0002_previsionmodel_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='previsionmodel',
            name='scaler_file',
            field=models.FileField(blank=True, null=True, upload_to='scalers/'),
        ),
    ]
