# Generated by Django 4.2.7 on 2024-02-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_alter_algorithm_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='name',
            field=models.CharField(choices=[('random_forest', 'Random Forest'), ('linear_regression', 'Regressão linear'), ('logistic_regression', 'Regressão logística'), ('svm', 'Support Vector Machines (SVM)')], max_length=200, unique=True),
        ),
    ]
