# Generated by Django 4.2.7 on 2024-02-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_alter_algorithm_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablesselection',
            name='variables_to_remove',
            field=models.JSONField(default=list),
        ),
    ]
