# Generated by Django 4.2.7 on 2024-02-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_variablesselection_variables_to_remove'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='trained',
            field=models.BooleanField(default=False),
        ),
    ]
