# Generated by Django 4.2.7 on 2024-02-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_training_trained'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='with_full_set',
            field=models.BooleanField(default=False),
        ),
    ]
