# Generated by Django 4.2.7 on 2024-02-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_training_bootstrap_training_importance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randomforest',
            name='algorithm_ptr',
        ),
        migrations.RemoveField(
            model_name='svm',
            name='algorithm_ptr',
        ),
        migrations.AddField(
            model_name='training',
            name='progress',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='name',
            field=models.CharField(choices=[('random_forest', 'Random Forest'), ('linear_regression', 'Linear regression'), ('KNN', 'KNN'), ('svm', 'Support Vector Machines (SVM)')], max_length=200),
        ),
        migrations.DeleteModel(
            name='LinearRegression',
        ),
        migrations.DeleteModel(
            name='RandomForest',
        ),
        migrations.DeleteModel(
            name='SVM',
        ),
    ]
