# Generated by Django 4.2.7 on 2024-03-14 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_remove_randomforest_algorithm_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BootstrapValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('molecules', models.JSONField(default=list)),
                ('R_value', models.FloatField()),
                ('R2_value', models.FloatField()),
                ('training_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.training')),
            ],
        ),
    ]
