# Generated by Django 4.2.7 on 2024-03-14 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_bootstrapvalues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bootstrapvalues',
            name='training_reference',
        ),
        migrations.AddField(
            model_name='bootstrapvalues',
            name='training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='training.training'),
        ),
    ]
