# Generated by Django 4.2.7 on 2024-05-23 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0014_remove_bootstrapvalues_training_reference_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariablesSelection',
        ),
    ]
