# Generated by Django 4.2.7 on 2024-07-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0015_delete_variablesselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='execution_type',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
