# Generated by Django 4.2.7 on 2024-08-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0016_training_execution_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='task_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
