# Generated by Django 4.2.7 on 2024-05-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables_selection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablesselection',
            name='rows_to_remove',
            field=models.JSONField(default=list),
        ),
    ]
