# Generated by Django 4.2.7 on 2024-05-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables_selection', '0002_variablesselection_rows_to_remove'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablesselection',
            name='modification_level',
            field=models.IntegerField(default=0),
        ),
    ]
