# Generated by Django 4.2.7 on 2024-05-31 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables_selection', '0003_variablesselection_modification_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variablesselection',
            name='modification_level',
        ),
        migrations.AddField(
            model_name='variablesselection',
            name='algorithm_progress',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
