# Generated by Django 4.2.7 on 2024-07-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables_selection', '0004_remove_variablesselection_modification_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablesselection',
            name='algorithm_execution_type',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
