# Generated by Django 4.2.7 on 2024-08-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables_selection', '0005_variablesselection_algorithm_execution_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablesselection',
            name='algorithm_task_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
