# Generated by Django 4.2.7 on 2024-08-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables_selection', '0006_variablesselection_algorithm_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablesselection',
            name='model',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
