# Generated by Django 4.2.7 on 2024-01-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='databases/')),
                ('file_separator', models.CharField(default=',', max_length=1)),
                ('lines', models.IntegerField()),
                ('columns', models.IntegerField()),
            ],
        ),
    ]
