# Generated by Django 4.2.7 on 2024-02-02 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Normalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('applied', models.BooleanField()),
                ('database', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.database')),
            ],
        ),
    ]
