# Generated by Django 4.2.7 on 2024-02-02 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_database_normalization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='normalization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.normalization'),
        ),
        migrations.AlterField(
            model_name='normalization',
            name='applied',
            field=models.BooleanField(default=False),
        ),
    ]
