# Generated by Django 4.2.7 on 2024-02-05 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_database_normalization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='normalization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.normalization'),
        ),
    ]
