# Generated by Django 4.2.7 on 2024-02-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_database_normalization'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='conversion_progress',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
