# Generated by Django 4.2.7 on 2024-02-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_database_conversion_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='columns',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='database',
            name='lines',
            field=models.IntegerField(default=0),
        ),
    ]
