# Generated by Django 4.2.7 on 2024-05-24 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_database_columns_alter_database_lines'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='databases/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('change_description', models.CharField(max_length=300)),
                ('actual_database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CSVDatabase', to='database.database')),
            ],
        ),
    ]
