# Generated by Django 4.2.7 on 2024-05-30 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_database_description_database_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
