# Generated by Django 4.2.7 on 2024-05-31 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0013_remove_project_database'),
        ('database', '0011_database_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='project_management.project'),
        ),
    ]
