# Generated by Django 4.2.7 on 2024-08-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_alter_database_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='file_message',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
